#!/usr/bin/env python
import os
import shutil
import torch
from diffusers import DiffusionPipeline

MODEL_CACHE = "model-cache"
if os.path.exists(MODEL_CACHE):
    shutil.rmtree(MODEL_CACHE)
os.makedirs(MODEL_CACHE, exist_ok=True)

pipe = DiffusionPipeline.from_pretrained(
    "camenduru/potat1",
    torch_dtype=torch.float16,
    variant="fp16",
    cache_dir=MODEL_CACHE,
)
